-- MySQL Script generated by MySQL Workbench
-- Wed Nov 29 23:32:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pssdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pssdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pssdb` DEFAULT CHARACTER SET utf8 ;
USE `pssdb` ;

-- -----------------------------------------------------
-- Table `pssdb`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pssdb`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `pssdb`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `modulo_administrativo` VARCHAR(1) NOT NULL,
  `modulo_funcionario` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pssdb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pssdb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `pssdb`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `senha` VARCHAR(64) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `devedor` VARCHAR(1) NOT NULL,
  `id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_tipo_usuario1_idx` (`id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `pssdb`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pssdb`.`tipo_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pssdb`.`tipo_produto` ;

CREATE TABLE IF NOT EXISTS `pssdb`.`tipo_produto` (
  `id_tipo_produto` INT NOT NULL,
  `nome_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pssdb`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pssdb`.`produto` ;

CREATE TABLE IF NOT EXISTS `pssdb`.`produto` (
  `id_produto` INT NOT NULL,
  `nome_produto` VARCHAR(45) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `desconto` DOUBLE NULL,
  `id_tipo_produto` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_produto_tipo_produto_idx` (`id_tipo_produto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_tipo_produto`
    FOREIGN KEY (`id_tipo_produto`)
    REFERENCES `pssdb`.`tipo_produto` (`id_tipo_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pssdb`.`tipo_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pssdb`.`tipo_pagamento` ;

CREATE TABLE IF NOT EXISTS `pssdb`.`tipo_pagamento` (
  `id_tipo_pagamento` INT NOT NULL,
  `nome_tipo_pagamento` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tipo_pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pssdb`.`atracao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pssdb`.`atracao` ;

CREATE TABLE IF NOT EXISTS `pssdb`.`atracao` (
  `id_atracao` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`id_atracao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pssdb`.`nota_fiscal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pssdb`.`nota_fiscal` ;

CREATE TABLE IF NOT EXISTS `pssdb`.`nota_fiscal` (
  `id_nota_fiscal` INT NOT NULL,
  `preco_total` DOUBLE NOT NULL,
  `data` DATE NOT NULL,
  `id_tipo_pagamento` INT NOT NULL,
  `id_atracao` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_nota_fiscal`),
  INDEX `fk_nota_fiscal_tipo_pagamento1_idx` (`id_tipo_pagamento` ASC) VISIBLE,
  INDEX `fk_nota_fiscal_atracao1_idx` (`id_atracao` ASC) VISIBLE,
  INDEX `fk_nota_fiscal_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_nota_fiscal_tipo_pagamento1`
    FOREIGN KEY (`id_tipo_pagamento`)
    REFERENCES `pssdb`.`tipo_pagamento` (`id_tipo_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_fiscal_atracao1`
    FOREIGN KEY (`id_atracao`)
    REFERENCES `pssdb`.`atracao` (`id_atracao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_fiscal_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `pssdb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pssdb`.`item_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pssdb`.`item_pedido` ;

CREATE TABLE IF NOT EXISTS `pssdb`.`item_pedido` (
  `id_produto` INT NOT NULL,
  `id_nota_fiscal` INT NOT NULL,
  `quantidade` INT NOT NULL,
  INDEX `fk_item_pedido_produto1_idx` (`id_produto` ASC) VISIBLE,
  INDEX `fk_item_pedido_nota_fiscal1_idx` (`id_nota_fiscal` ASC) VISIBLE,
  PRIMARY KEY (`id_produto`, `id_nota_fiscal`),
  CONSTRAINT `fk_item_pedido_produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `pssdb`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_pedido_nota_fiscal1`
    FOREIGN KEY (`id_nota_fiscal`)
    REFERENCES `pssdb`.`nota_fiscal` (`id_nota_fiscal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pssdb`.`tipo_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `pssdb`;
INSERT INTO `pssdb`.`tipo_usuario` (`id_tipo_usuario`, `nome`, `modulo_administrativo`, `modulo_funcionario`) VALUES (1, 'Administrador', 'S', 'S');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pssdb`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `pssdb`;
INSERT INTO `pssdb`.`usuario` (`id_usuario`, `nome`, `sobrenome`, `data_nascimento`, `cpf`, `senha`, `telefone`, `devedor`, `id_tipo_usuario`) VALUES (1, 'Antonio', 'Farias', '1980-01-30', '555444', '1234', '16997665544', 'N', 1);

COMMIT;

