
package view;

import controller.LogTrack;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.Timer;
import model.Usuario;
import view.JFrameAtracaoCRUD;
import view.JFrameAtracaoCRUD;
import view.JFrameConsultaAtracao;
import view.JFrameConsultaAtracao;
import view.JFrameConsultaItemPedido;
import view.JFrameConsultaItemPedido;
import view.JFrameItemPedidoCRUD;
import view.JFrameItemPedidoCRUD;

public class JFrameSistemaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrameSistema
     */
    public JFrameSistemaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDelicia = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBarActions = new javax.swing.JMenuBar();
        jMenuAdministrativo = new javax.swing.JMenu();
        jMenuItemCadastroUsuario = new javax.swing.JMenuItem();
        jMenuItemCadastroTipoUsuario = new javax.swing.JMenuItem();
        jMenuItemCadastroItemPedido = new javax.swing.JMenuItem();
        jMenuItemCadastroAtracao = new javax.swing.JMenuItem();
        jMenuItemCadastroTipoProduto = new javax.swing.JMenuItem();
        jMenuItemCadastroProduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemConsultaUsuario = new javax.swing.JMenuItem();
        jMenuItemConsultaTipoUsuario = new javax.swing.JMenuItem();
        jMenuItemConsultaItemPedido = new javax.swing.JMenuItem();
        jMenuItemConsultaAtracao = new javax.swing.JMenuItem();
        jMenuItemConsultaTipoProduto = new javax.swing.JMenuItem();
        jMenuItemConsultaProdutos = new javax.swing.JMenuItem();
        jMenuAtendimento = new javax.swing.JMenu();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemUsuarioSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema - La Delicia");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDelicia.setFont(new java.awt.Font("Zilla Slab", 3, 48)); // NOI18N
        jLabelDelicia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/titulo.png"))); // NOI18N
        jLabelDelicia.setText("La Delicia");
        jLabelDelicia.setFocusable(false);
        jLabelDelicia.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabelDelicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 500, 90));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setText("Pratos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 680));

        jMenuAdministrativo.setText("Administrativo");

        jMenuItemCadastroUsuario.setText("Cadastro Usuario");
        jMenuItemCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroUsuarioActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroUsuario);

        jMenuItemCadastroTipoUsuario.setText("Cadastro Tipo Usuario");
        jMenuItemCadastroTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroTipoUsuarioActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroTipoUsuario);

        jMenuItemCadastroItemPedido.setText("Cadastro Item Pedido");
        jMenuItemCadastroItemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroItemPedidoActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroItemPedido);

        jMenuItemCadastroAtracao.setText("Cadastro Atração");
        jMenuItemCadastroAtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroAtracaoActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroAtracao);

        jMenuItemCadastroTipoProduto.setText("Cadastro Tipo Produto");
        jMenuItemCadastroTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroTipoProdutoActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroTipoProduto);

        jMenuItemCadastroProduto.setText("Cadastro Produto");
        jMenuItemCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroProdutoActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroProduto);
        jMenuAdministrativo.add(jSeparator1);

        jMenuItemConsultaUsuario.setText("Consulta Usuario");
        jMenuItemConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaUsuarioActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaUsuario);

        jMenuItemConsultaTipoUsuario.setText("Consulta Tipo Usuario");
        jMenuItemConsultaTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaTipoUsuarioActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaTipoUsuario);

        jMenuItemConsultaItemPedido.setText("Consulta Item Pedido");
        jMenuItemConsultaItemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaItemPedidoActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaItemPedido);

        jMenuItemConsultaAtracao.setText("Consulta Atração");
        jMenuItemConsultaAtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaAtracaoActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaAtracao);

        jMenuItemConsultaTipoProduto.setText("Consulta Tipo Produto");
        jMenuItemConsultaTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaTipoProdutoActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaTipoProduto);

        jMenuItemConsultaProdutos.setText("Consulta Produto");
        jMenuItemConsultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaProdutosActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaProdutos);

        jMenuBarActions.add(jMenuAdministrativo);

        jMenuAtendimento.setText("Atendimento");
        jMenuBarActions.add(jMenuAtendimento);

        jMenuUsuario.setText("Usuario");

        jMenuItemUsuarioSair.setText("Sair");
        jMenuItemUsuarioSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioSairActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemUsuarioSair);

        jMenuBarActions.add(jMenuUsuario);

        setJMenuBar(jMenuBarActions);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemCadastroItemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroItemPedidoActionPerformed
        try {
            JFrameItemPedidoCRUD jFrameCRUD;
            jFrameCRUD = new JFrameItemPedidoCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroItemPedidoActionPerformed

    private void jMenuItemConsultaItemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaItemPedidoActionPerformed
        try {
            JFrameConsultaItemPedido jFrameConsulta;
            jFrameConsulta = new JFrameConsultaItemPedido( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaItemPedidoActionPerformed

    private void jMenuItemCadastroAtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroAtracaoActionPerformed
        try {
            JFrameAtracaoCRUD jFrameCRUD;
            jFrameCRUD = new JFrameAtracaoCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroAtracaoActionPerformed

    private void jMenuItemConsultaAtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaAtracaoActionPerformed
        try {
            JFrameConsultaAtracao jFrameConsulta;
            jFrameConsulta = new JFrameConsultaAtracao( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaAtracaoActionPerformed

    private void jMenuItemCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroUsuarioActionPerformed
        try {
            JFrameUsuarioCRUD jFrameCRUD;
            jFrameCRUD = new JFrameUsuarioCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroUsuarioActionPerformed

    private void jMenuItemCadastroTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroTipoProdutoActionPerformed
        try {
            JFrameTipoProdutoCRUD jFrameCRUD;
            jFrameCRUD = new JFrameTipoProdutoCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroTipoProdutoActionPerformed

    private void jMenuItemConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaUsuarioActionPerformed
        try {
            JFrameConsultaUsuario jFrameConsulta;
            jFrameConsulta = new JFrameConsultaUsuario( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaUsuarioActionPerformed

    private void jMenuItemCadastroTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroTipoUsuarioActionPerformed
        try {
            JFrameTipoUsuarioCRUD jFrameCRUD;
            jFrameCRUD = new JFrameTipoUsuarioCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroTipoUsuarioActionPerformed

    private void jMenuItemConsultaTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaTipoUsuarioActionPerformed
        try {
            JFrameConsultaTipoUsuario jFrameConsulta;
            jFrameConsulta = new JFrameConsultaTipoUsuario( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaTipoUsuarioActionPerformed

    private void jMenuItemUsuarioSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioSairActionPerformed
        //logout();
    }//GEN-LAST:event_jMenuItemUsuarioSairActionPerformed

    private void jMenuItemConsultaTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaTipoProdutoActionPerformed
        try {
            JFrameConsultaTipoProduto jFrameConsulta;
            jFrameConsulta = new JFrameConsultaTipoProduto( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaTipoProdutoActionPerformed

    private void jMenuItemCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroProdutoActionPerformed
        try {
            JFrameProdutoCRUD jFrameCRUD;
            jFrameCRUD = new JFrameProdutoCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroProdutoActionPerformed

    private void jMenuItemConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaProdutosActionPerformed
        try {
            JFrameConsultaProduto jFrameConsulta;
            jFrameConsulta = new JFrameConsultaProduto( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaProdutosActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameSistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameSistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameSistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameSistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFrameSistema().setVisible(true);
//            }
//        });
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFrameSistema().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabelDelicia;
    private javax.swing.JMenu jMenuAdministrativo;
    private javax.swing.JMenu jMenuAtendimento;
    private javax.swing.JMenuBar jMenuBarActions;
    private javax.swing.JMenuItem jMenuItemCadastroAtracao;
    private javax.swing.JMenuItem jMenuItemCadastroItemPedido;
    private javax.swing.JMenuItem jMenuItemCadastroProduto;
    private javax.swing.JMenuItem jMenuItemCadastroTipoProduto;
    private javax.swing.JMenuItem jMenuItemCadastroTipoUsuario;
    private javax.swing.JMenuItem jMenuItemCadastroUsuario;
    private javax.swing.JMenuItem jMenuItemConsultaAtracao;
    private javax.swing.JMenuItem jMenuItemConsultaItemPedido;
    private javax.swing.JMenuItem jMenuItemConsultaProdutos;
    private javax.swing.JMenuItem jMenuItemConsultaTipoProduto;
    private javax.swing.JMenuItem jMenuItemConsultaTipoUsuario;
    private javax.swing.JMenuItem jMenuItemConsultaUsuario;
    private javax.swing.JMenuItem jMenuItemUsuarioSair;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
