
package view;

import controller.LogTrack;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.Timer;
import model.Usuario;

/**
 *
 * @author saradu
 */
public class JFrameLogin extends javax.swing.JFrame {
    private Usuario usuario;
    
    //barrinha
    private Timer tiempo;
    int contador;
    int segundos = 20;
    
    /**
     * Creates new form JFramePrincipal
     */
    
    public JFrameLogin() {
        initComponents();
        
        logout();
    }
    
        
    private void logout() {
        
        usuario = new Usuario();
        
        //jMenuAdministrativo.setEnabled(false);
        //jMenuAtendimento.setEnabled(false);
        //jMenuAtendimento.setEnabled(false);

        
        jPanelLogin.setVisible(true);
        
    }
    
    private void login() {
        
       
        jTextFieldUsuario.setText("");
        jPasswordFieldSenha.setText("");
        
        jProgressBarProgresso.setVisible(true);
        contador = -1;
        jProgressBarProgresso.setValue(0);
        jProgressBarProgresso.setStringPainted(true);
        tiempo = new Timer(segundos, new BarraProgreso());
        tiempo.start(); 
                
        //jPanelLogin.setVisible(false);
        
        //if( usuario.getTipoUsuario().getModuloAdministrativo().equals("S") ) {
            //jMenuAdministrativo.setEnabled(true);
        //}
        
        //if( usuario.getTipoUsuario().getModuloAgendamento().equals("S") ) {
            //jMenuAtendimento.setEnabled(true);
        //}
        
        //if( usuario.getTipoUsuario().getModuloAtendimento().equals("S") ) {
            //jMenuAtendimento.setEnabled(true);
       // }
               
    }
    
    public class BarraProgreso implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            contador++;
            jProgressBarProgresso.setValue(contador);
            if (contador == 100) {
                tiempo.stop();
                if (jProgressBarProgresso.getValue() == 100) {
                    JFrameSistemaPrincipal sis = new JFrameSistemaPrincipal();
                    sis.setVisible(true);
                    dispose();
                }
            }
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelIniciarSessao = new javax.swing.JLabel();
        jProgressBarProgresso = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLogin.setBackground(new java.awt.Color(153, 153, 153));
        jPanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUsuario.setText("Usuário:");
        jPanelLogin.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSenha.setText("Senha:");
        jPanelLogin.add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jTextFieldUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        jPanelLogin.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 250, 35));

        jPasswordFieldSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldSenha.setBorder(null);
        jPanelLogin.add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 250, 35));

        jButtonLogin.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLogin.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Login");
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 93, 35));

        jButtonSair.setBackground(new java.awt.Color(204, 0, 0));
        jButtonSair.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 93, 35));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabelIniciarSessao.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        jLabelIniciarSessao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIniciarSessao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIniciarSessao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iniciar.png"))); // NOI18N
        jLabelIniciarSessao.setText("Iniciar Sessão");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIniciarSessao, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIniciarSessao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jPanelLogin.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 110));

        jProgressBarProgresso.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBarProgresso.setForeground(new java.awt.Color(0, 110, 255));
        jPanelLogin.add(jProgressBarProgresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 250, 30));

        getContentPane().add(jPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        login();
               
//        try {
//            
//            usuario.setIdUsuario( Integer.parseInt( jTextFieldUsuario.getText() ) );
//            usuario.load();
//            
//            Usuario usLogin = new Usuario();
//            
//            usLogin.setIdUsuario( Integer.parseInt( jTextFieldUsuario.getText() ) );
//            //usLogin.setSenhaAcesso( jPasswordFieldSenha.getText() );
//            
////            if( usuario.getSenhaAcesso().equals( 
////                    usLogin.getSenhaAcesso() ) ) {
////                login();
////                usuario.disconnectFromDatabase();
////            } else {
////                throw new Exception("Senha Inválida!");
////            }
//            
//        
//        } catch(Exception ex) {
//            LogTrack.getInstance().addException(ex, true, this);
//        }
         
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelIniciarSessao;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JProgressBar jProgressBarProgresso;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
