
package view;

import controller.LogTrack;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.Timer;
import model.Usuario;
import view.JFrameAtracaoCRUD;
import view.JFrameAtracaoCRUD;
import view.JFrameConsultaAtracao;
import view.JFrameConsultaAtracao;
import view.JFrameConsultaItemPedido;
import view.JFrameConsultaItemPedido;
import view.JFrameItemPedidoCRUD;
import view.JFrameItemPedidoCRUD;

public class JFrameSistemaPrincipal extends javax.swing.JFrame {
    private Usuario usuario;
    
    /**
     * Creates new form JFrameSistema
     */
    public JFrameSistemaPrincipal() {
        initComponents();
        logout();
    }
    
    private void logout() {
        
        usuario = new Usuario();
        jTextFieldUsuario.setText("");
        jPasswordFieldSenha.setText("");
        jLabelDelicia.setVisible(false);
        jMenuAdministrativo.setEnabled(false);
        jMenuAtendimento.setEnabled(false);
        jMenuUsuario.setEnabled(false);
        jPanelLogin.setVisible(true);
        
    }
    
    private void login() {
        
       
        jTextFieldUsuario.setText("");
        jPasswordFieldSenha.setText("");
        jLabelBemvindo.setEnabled(true);
        jLabelBemvindo.setText("Bem-vindo/a, " + usuario.getNome() + "!");
        jLabelDelicia.setVisible(true);
                
        jPanelLogin.setVisible(false);
        
        if( usuario.getTipoUsuario().getModuloAdministrativo().equals("S") ) {
            jMenuAdministrativo.setEnabled(true);
        }
        
        if( usuario.getTipoUsuario().getModuloFuncionario().equals("S") ) {
            jMenuAtendimento.setEnabled(true);
        }
        
        jMenuUsuario.setEnabled(true);
        
               
    }       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDelicia = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelBemvindo = new javax.swing.JLabel();
        jPanelLogin = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabelIniciarSessao = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jMenuBarActions = new javax.swing.JMenuBar();
        jMenuAdministrativo = new javax.swing.JMenu();
        jMenuItemCadastroUsuario = new javax.swing.JMenuItem();
        jMenuItemCadastroTipoUsuario = new javax.swing.JMenuItem();
        jMenuItemCadastroItemPedido = new javax.swing.JMenuItem();
        jMenuItemCadastroAtracao = new javax.swing.JMenuItem();
        jMenuItemCadastroTipoProduto = new javax.swing.JMenuItem();
        jMenuItemCadastroProduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemConsultaUsuario = new javax.swing.JMenuItem();
        jMenuItemConsultaTipoUsuario = new javax.swing.JMenuItem();
        jMenuItemConsultaItemPedido = new javax.swing.JMenuItem();
        jMenuItemConsultaAtracao = new javax.swing.JMenuItem();
        jMenuItemConsultaTipoProduto = new javax.swing.JMenuItem();
        jMenuItemConsultaProdutos = new javax.swing.JMenuItem();
        jMenuAtendimento = new javax.swing.JMenu();
        jMenuItemConsultaUsuario1 = new javax.swing.JMenuItem();
        jMenuItemConsultaTipoUsuario1 = new javax.swing.JMenuItem();
        jMenuItemConsultaItemPedido1 = new javax.swing.JMenuItem();
        jMenuItemConsultaTipoProduto1 = new javax.swing.JMenuItem();
        jMenuItemConsultaAtracao1 = new javax.swing.JMenuItem();
        jMenuItemConsultaProdutos1 = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemUsuarioSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema - La Delicia");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDelicia.setFont(new java.awt.Font("Zilla Slab", 3, 48)); // NOI18N
        jLabelDelicia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/titulo.png"))); // NOI18N
        jLabelDelicia.setText("La Delicia");
        jLabelDelicia.setFocusable(false);
        jLabelDelicia.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabelDelicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 370, 90));

        jPanelMenu.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setText("Pratos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jLabelBemvindo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBemvindo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBemvindo.setText("Bem-vindo!");
        jLabelBemvindo.setEnabled(false);

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelBemvindo)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBemvindo)
                .addGap(204, 204, 204)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 680));

        jPanelLogin.setBackground(new java.awt.Color(153, 153, 153));
        jPanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUsuario.setText("Usuário:");
        jPanelLogin.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSenha.setText("Senha:");
        jPanelLogin.add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jTextFieldUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        jPanelLogin.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 250, 35));

        jPasswordFieldSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldSenha.setBorder(null);
        jPanelLogin.add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 250, 35));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabelIniciarSessao.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        jLabelIniciarSessao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIniciarSessao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIniciarSessao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iniciar.png"))); // NOI18N
        jLabelIniciarSessao.setText("Iniciar Sessão");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIniciarSessao, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIniciarSessao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jPanelLogin.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 110));

        jButtonLogin.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLogin.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Login");
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 250, 35));

        jButtonSair.setBackground(new java.awt.Color(204, 0, 0));
        jButtonSair.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 250, 35));

        getContentPane().add(jPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 310, 410));

        jMenuAdministrativo.setText("Administrativo");

        jMenuItemCadastroUsuario.setText("Cadastro Usuario");
        jMenuItemCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroUsuarioActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroUsuario);

        jMenuItemCadastroTipoUsuario.setText("Cadastro Tipo Usuario");
        jMenuItemCadastroTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroTipoUsuarioActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroTipoUsuario);

        jMenuItemCadastroItemPedido.setText("Cadastro Item Pedido");
        jMenuItemCadastroItemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroItemPedidoActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroItemPedido);

        jMenuItemCadastroAtracao.setText("Cadastro Atração");
        jMenuItemCadastroAtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroAtracaoActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroAtracao);

        jMenuItemCadastroTipoProduto.setText("Cadastro Tipo Produto");
        jMenuItemCadastroTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroTipoProdutoActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroTipoProduto);

        jMenuItemCadastroProduto.setText("Cadastro Produto");
        jMenuItemCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroProdutoActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroProduto);
        jMenuAdministrativo.add(jSeparator1);

        jMenuItemConsultaUsuario.setText("Consulta Usuario");
        jMenuItemConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaUsuarioActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaUsuario);

        jMenuItemConsultaTipoUsuario.setText("Consulta Tipo Usuario");
        jMenuItemConsultaTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaTipoUsuarioActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaTipoUsuario);

        jMenuItemConsultaItemPedido.setText("Consulta Item Pedido");
        jMenuItemConsultaItemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaItemPedidoActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaItemPedido);

        jMenuItemConsultaAtracao.setText("Consulta Atração");
        jMenuItemConsultaAtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaAtracaoActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaAtracao);

        jMenuItemConsultaTipoProduto.setText("Consulta Tipo Produto");
        jMenuItemConsultaTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaTipoProdutoActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaTipoProduto);

        jMenuItemConsultaProdutos.setText("Consulta Produto");
        jMenuItemConsultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaProdutosActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaProdutos);

        jMenuBarActions.add(jMenuAdministrativo);

        jMenuAtendimento.setText("Atendimento");

        jMenuItemConsultaUsuario1.setText("Consulta Usuario");
        jMenuItemConsultaUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaUsuario1ActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemConsultaUsuario1);

        jMenuItemConsultaTipoUsuario1.setText("Consulta Tipo Usuario");
        jMenuItemConsultaTipoUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaTipoUsuario1ActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemConsultaTipoUsuario1);

        jMenuItemConsultaItemPedido1.setText("Consulta Item Pedido");
        jMenuItemConsultaItemPedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaItemPedido1ActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemConsultaItemPedido1);

        jMenuItemConsultaTipoProduto1.setText("Consulta Tipo Produto");
        jMenuItemConsultaTipoProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaTipoProduto1ActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemConsultaTipoProduto1);

        jMenuItemConsultaAtracao1.setText("Consulta Atração");
        jMenuItemConsultaAtracao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaAtracao1ActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemConsultaAtracao1);

        jMenuItemConsultaProdutos1.setText("Consulta Produto");
        jMenuItemConsultaProdutos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaProdutos1ActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemConsultaProdutos1);

        jMenuBarActions.add(jMenuAtendimento);

        jMenuUsuario.setText("Usuario");

        jMenuItemUsuarioSair.setText("Sair");
        jMenuItemUsuarioSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioSairActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemUsuarioSair);

        jMenuBarActions.add(jMenuUsuario);

        setJMenuBar(jMenuBarActions);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemCadastroItemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroItemPedidoActionPerformed
        try {
            JFrameItemPedidoCRUD jFrameCRUD;
            jFrameCRUD = new JFrameItemPedidoCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroItemPedidoActionPerformed

    private void jMenuItemConsultaItemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaItemPedidoActionPerformed
        try {
            JFrameConsultaItemPedido jFrameConsulta;
            jFrameConsulta = new JFrameConsultaItemPedido( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaItemPedidoActionPerformed

    private void jMenuItemCadastroAtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroAtracaoActionPerformed
        try {
            JFrameAtracaoCRUD jFrameCRUD;
            jFrameCRUD = new JFrameAtracaoCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroAtracaoActionPerformed

    private void jMenuItemConsultaAtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaAtracaoActionPerformed
        try {
            JFrameConsultaAtracao jFrameConsulta;
            jFrameConsulta = new JFrameConsultaAtracao( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaAtracaoActionPerformed

    private void jMenuItemCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroUsuarioActionPerformed
        try {
            JFrameUsuarioCRUD jFrameCRUD;
            jFrameCRUD = new JFrameUsuarioCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroUsuarioActionPerformed

    private void jMenuItemCadastroTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroTipoProdutoActionPerformed
        try {
            JFrameTipoProdutoCRUD jFrameCRUD;
            jFrameCRUD = new JFrameTipoProdutoCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroTipoProdutoActionPerformed

    private void jMenuItemConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaUsuarioActionPerformed
        try {
            JFrameConsultaUsuario jFrameConsulta;
            jFrameConsulta = new JFrameConsultaUsuario( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaUsuarioActionPerformed

    private void jMenuItemCadastroTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroTipoUsuarioActionPerformed
        try {
            JFrameTipoUsuarioCRUD jFrameCRUD;
            jFrameCRUD = new JFrameTipoUsuarioCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroTipoUsuarioActionPerformed

    private void jMenuItemConsultaTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaTipoUsuarioActionPerformed
        try {
            JFrameConsultaTipoUsuario jFrameConsulta;
            jFrameConsulta = new JFrameConsultaTipoUsuario( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaTipoUsuarioActionPerformed

    private void jMenuItemUsuarioSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioSairActionPerformed
        logout();
    }//GEN-LAST:event_jMenuItemUsuarioSairActionPerformed

    private void jMenuItemConsultaTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaTipoProdutoActionPerformed
        try {
            JFrameConsultaTipoProduto jFrameConsulta;
            jFrameConsulta = new JFrameConsultaTipoProduto( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaTipoProdutoActionPerformed

    private void jMenuItemCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroProdutoActionPerformed
        try {
            JFrameProdutoCRUD jFrameCRUD;
            jFrameCRUD = new JFrameProdutoCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroProdutoActionPerformed

    private void jMenuItemConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaProdutosActionPerformed
        try {
            JFrameConsultaProduto jFrameConsulta;
            jFrameConsulta = new JFrameConsultaProduto( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaProdutosActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed

    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed

        //login();
        
        try {
            
            usuario.setIdUsuario( Integer.parseInt( jTextFieldUsuario.getText() ) );
            usuario.load();
            
            Usuario usLogin = new Usuario();
            
            usLogin.setIdUsuario( Integer.parseInt( jTextFieldUsuario.getText() ) );
            usLogin.setSenha( jPasswordFieldSenha.getText() );
            
            if( usuario.getSenha().equals( usLogin.getSenha() ) ) {
                login();
                usuario.disconnectFromDatabase();
            } else {
                jTextFieldUsuario.setText("");
                jPasswordFieldSenha.setText("");  
                throw new Exception("Senha Inválida!");              
            }
            
        
        } catch(Exception ex) {
            LogTrack.getInstance().addException( ex, true, this );
        }
         
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jMenuItemConsultaUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemConsultaUsuario1ActionPerformed

    private void jMenuItemConsultaTipoUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaTipoUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemConsultaTipoUsuario1ActionPerformed

    private void jMenuItemConsultaItemPedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaItemPedido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemConsultaItemPedido1ActionPerformed

    private void jMenuItemConsultaTipoProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaTipoProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemConsultaTipoProduto1ActionPerformed

    private void jMenuItemConsultaAtracao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaAtracao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemConsultaAtracao1ActionPerformed

    private void jMenuItemConsultaProdutos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaProdutos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemConsultaProdutos1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameSistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameSistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameSistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameSistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameSistemaPrincipal().setVisible(true);
            }
        });
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFrameSistema().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelBemvindo;
    private javax.swing.JLabel jLabelDelicia;
    private javax.swing.JLabel jLabelIniciarSessao;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenuAdministrativo;
    private javax.swing.JMenu jMenuAtendimento;
    private javax.swing.JMenuBar jMenuBarActions;
    private javax.swing.JMenuItem jMenuItemCadastroAtracao;
    private javax.swing.JMenuItem jMenuItemCadastroItemPedido;
    private javax.swing.JMenuItem jMenuItemCadastroProduto;
    private javax.swing.JMenuItem jMenuItemCadastroTipoProduto;
    private javax.swing.JMenuItem jMenuItemCadastroTipoUsuario;
    private javax.swing.JMenuItem jMenuItemCadastroUsuario;
    private javax.swing.JMenuItem jMenuItemConsultaAtracao;
    private javax.swing.JMenuItem jMenuItemConsultaAtracao1;
    private javax.swing.JMenuItem jMenuItemConsultaItemPedido;
    private javax.swing.JMenuItem jMenuItemConsultaItemPedido1;
    private javax.swing.JMenuItem jMenuItemConsultaProdutos;
    private javax.swing.JMenuItem jMenuItemConsultaProdutos1;
    private javax.swing.JMenuItem jMenuItemConsultaTipoProduto;
    private javax.swing.JMenuItem jMenuItemConsultaTipoProduto1;
    private javax.swing.JMenuItem jMenuItemConsultaTipoUsuario;
    private javax.swing.JMenuItem jMenuItemConsultaTipoUsuario1;
    private javax.swing.JMenuItem jMenuItemConsultaUsuario;
    private javax.swing.JMenuItem jMenuItemConsultaUsuario1;
    private javax.swing.JMenuItem jMenuItemUsuarioSair;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
